-- Sprint 6a-8: Campos de anulación y edición.
ALTER TABLE loans ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS cancel_reason TEXT DEFAULT NULL;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS edited_at TIMESTAMPTZ DEFAULT NULL;

ALTER TABLE payments ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS cancel_reason TEXT DEFAULT NULL;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS edited_at TIMESTAMPTZ DEFAULT NULL;

ALTER TABLE clients ADD COLUMN IF NOT EXISTS edited_at TIMESTAMPTZ DEFAULT NULL;
